spring:
  http:
    encoding:
      force: true
  freemarker:
    cache: false
server:
  port: 8080

dubbo:
  container: spring
  application:
    name: demo-provider
    owner: chengli
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    client: zkclient
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 20882
    path: learning
  service:
    loadbalance: roundrobin
    validation: false
